apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../base

patchesStrategicMerge:
- overlay-ingress.yml

namespace: ${KUBE_NAMESPACE}

namePrefix: ${CI_ENVIRONMENT_SLUG}-${LF_NAME}-

commonLabels:
  app: ${CI_ENVIRONMENT_SLUG}-${LF_NAME}

images:
  - name: lf-image
    newName: ${CI_REGISTRY_IMAGE}/${CI_COMMIT_REF_SLUG}
    newTag: ${CI_COMMIT_SHA}
