apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress
spec:
  tls:
  - hosts:
    - ${CI_ENVIRONMENT_SLUG}.${LF_SUBDOMAIN}.${KUBE_INGRESS_BASE_DOMAIN}
    secretName: ${CI_ENVIRONMENT_SLUG}-apps-lostfoil-com
  rules:
  - host: ${CI_ENVIRONMENT_SLUG}.${LF_SUBDOMAIN}.${KUBE_INGRESS_BASE_DOMAIN}
    http:
      paths:
      - path: /
        backend:
          serviceName: svc
          servicePort: 80
