# Rename this file to config.yml or use -c flag
server:
  host: 0.0.0.0
  port: 8080
  jwt_secret: superSecret # change this!
twilio:
  sid: AC0xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx # Replace with your Twilio Account SID
  token: f87xx0x0x0x0x0x0x0x0x0x0x0x0x0 # Replace with your Twilio Account Token
  whatsapp_from: whatsapp:+14155238886 # Replace with your Twilio WhatsApp mobile number
  # Username password for basic auth in Twilio webhook
  # use https://webhook_user:webhook_password@example.com/api/v1/incoming as webhook url
  webhook_user: twilio
  webhook_password: whookpass
database:
  path: gonotify.db # path for sqlite3 database

# Your Twilio whatsapp number must have templates aligning with below values
templates:
  # available variables:
  # Code - verification code
  verify: "Your GoNotify code is {{.Code}}"
  # I know this doesn't make sense, but this aligns with one of the template
  # provided by Twilio whatsapp sandbox
  # available variables:
  # Total - number of notifications pending
  notification: "Your appointment is coming up on today at notification"
