apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      component: app
  template:
    metadata:
      labels:
        component: app
    spec:
      containers:
      - name: app
        image: lf-image
        ports:
        - containerPort: 3333
      imagePullSecrets:
        - name: regcred
